README.org --- description



Copyright (C) 2013 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of black-white-sensor.

  black-white-sensor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  black-white-sensor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with black-white-sensor.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
  optic photo optocouple line sensor black white



* Description:
  

* Usage:
  use it



* History:
  Version 0.1 was created at 2013-05(May)-26


* Dependences:
  

